### ISSUE TITLE
Implement toString() override

### ISSUE THREAD

**Issue by NnoukK** [NnoukK/titanic-journey#14]
É necessário implementar este método nas classes Expo, Room, Category e ArtPiece, para mostrar o nome e/ou id do objecto nas listas presentes nos forms

**Comment by NnoukK** [comment]
Uma boa approach para implementação disto é a seguinte: [https://stackoverflow.com/a/38922369](url)

**Comment by Cariocecuz** [comment]
ja fostes 9892fda950c972d5607d954f2eba47ce230628ab
